# Default values for fh-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

## ------------------------------------------------------
## FH Ingress
## ------------------------------------------------------
fh-ingress:
  enabled: true
  staticIpName: fh-static-ip

## ------------------------------------------------------
## FH Ingress
## ------------------------------------------------------
cp-zookeeper:
  servers: 3
  minAvailable: 2
  persistence:
    enabled: true
    dataDirSize: 5Gi
    dataDirStorageClass: standard
    dataLogDirSize: 5Gi
    dataLogDirStorageClass: standard
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
cp-kafka:
  brokers: 6
  configurationOverrides:
    "offsets.topic.replication.factor": "2"
    "default.replication.factor": 2
    "min.insync.replicas": 1
    "auto.create.topics.enable": false
    "num.partitions": 20
    "log.flush.interval.messages": 20000
    "log.flush.interval.ms": 1000
    "num.replica.fetchers": 2
  persistence:
    enabled: true
    size: 200Gi
    storageClass: standard
  heapOptions: "-Xmx16384m -Xms16384m"
  resources:
    requests:
      cpu: 500m
      memory: 16384Mi
    limits:
      cpu: 2000m
      memory: 16384Mi
  prometheus:
    jmx:
      enabled: false
  cp-zookeeper:
    enabled: false
    url: "fh-cloud-cp-zookeeper-headless.fh-cloud:2181"


## ------------------------------------------------------
## Schema Registry
## ------------------------------------------------------
cp-schema-registry:
  image: confluentinc/cp-schema-registry
  imageTag: 5.1.0
  heapOptions: "-Xms1024M -Xmx1024M"
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

## ------------------------------------------------------
## Hadoop
## ------------------------------------------------------
hadoop:
  hdfs:
    nameNode:
      pdbMinAvailable: 1
    dataNode:
      replicas: 1
      pdbMinAvailable: 1
  persistence:
    nameNode:
      enabled: true
      storageClass: "standard"
      accessMode: ReadWriteOnce
      size: 50Gi
    dataNode:
      enabled: true
      storageClass: "standard"
      accessMode: ReadWriteOnce
      size: 200Gi

## ------------------------------------------------------
## Crate
## ------------------------------------------------------
crate:
  persistence:
    enabled: false
    storageClass: standard
    size: 4096Gi

## ------------------------------------------------------
## FH Producer
## ------------------------------------------------------
fh-producer:
  image: asia.gcr.io/jc1804-220407/fh-producer:1.2.10

## ------------------------------------------------------
## FH Endpoint
## ------------------------------------------------------
fh-endpoint:
  image: asia.gcr.io/jc1804-220407/fh-endpoint:1.6.4

## ------------------------------------------------------
## FH ETL
## ------------------------------------------------------
fh-etl:
  replicas: 2
  image: asia.gcr.io/jc1804-220407/fh-analytics-kafka:1.9.4
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: standard

## ------------------------------------------------------
## FH Analytics Alerts
## ------------------------------------------------------
fh-analytics-alerts:
  replicas: 1
  image: asia.gcr.io/jc1804-220407/fh-analytics-kafka:1.9.4
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: standard 

## ------------------------------------------------------
## FH Analytics Global Averages
## ------------------------------------------------------
fh-analytics-global-averages:
  replicas: 1
  image: asia.gcr.io/jc1804-220407/fh-analytics-kafka:1.9.4
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: standard

## ------------------------------------------------------
## FH Analytics Minutely
## ------------------------------------------------------
fh-analytics-minutely:
  replicas: 1
  image: asia.gcr.io/jc1804-220407/fh-analytics-kafka:1.9.4
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 4000m
      memory: 2048Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: standard

## ------------------------------------------------------
## FH Analytics Sessionization
## ------------------------------------------------------
fh-analytics-sessionization:
  replicas: 3
  image: asia.gcr.io/jc1804-220407/fh-analytics-kafka:1.9.4
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 4096Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: standard

## ------------------------------------------------------
## FH Sink Aggregated Records
## ------------------------------------------------------
fh-sink-adwin-alerts:
  replicas: 1
  image: asia.gcr.io/jc1804-220407/fh-analytics-kafka:1.9.4
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: standard

## ------------------------------------------------------
## FH Sink Aggregated Records
## ------------------------------------------------------
fh-sink-aggregated-records:
  replicas: 2
  image: asia.gcr.io/jc1804-220407/fh-analytics-kafka:1.9.4
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: standard

## ------------------------------------------------------
## FH Sink Alerts
## ------------------------------------------------------
fh-sink-alerts:
  replicas: 1
  image: asia.gcr.io/jc1804-220407/fh-analytics-kafka:1.9.4
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: standard

## ------------------------------------------------------
## FH Sink Global Averages
## ------------------------------------------------------
fh-sink-global-averages:
  replicas: 1
  image: asia.gcr.io/jc1804-220407/fh-analytics-kafka:1.9.4
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: standard

## ------------------------------------------------------
## FH Throughput
## ------------------------------------------------------
fh-throughput:
  image: asia.gcr.io/jc1804-220407/fh-analytics-kafka:1.9.4
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: standard

## ------------------------------------------------------
## FH Chart
## ------------------------------------------------------
fh-chart:
  image: asia.gcr.io/jc1804-220407/fh-chart:1.3.4
  apiUrl: "http://35.244.192.244/api"

## ------------------------------------------------------
## FH Measurer
## ------------------------------------------------------
fh-measurer:
  image: asia.gcr.io/jc1804-220407/fh-measurer:1.1.1