apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.Release.Name}}-fh-producer-normal"
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app.kubernetes.io/name: "{{.Release.Name}}-fh-producer-normal"
spec:
  replicas: 6
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{.Release.Name}}-fh-producer-normal"
    spec:
      containers:
      - env:
        - name: CONCURRENT_CONNECTIONS
          value: "16"
        - name: NUM_OF_PEOPLE
          value: "40000"
        - name: NUM_OF_PEOPLE_PER_ITERATION
          value: "50"
        - name: MAX_NUM_OF_HUB_RECORD_BATCHES
          value: "10000"
        - name: MAX_NUM_OF_HUB_RECORDS
          value: "100000"
        - name: MAX_NUM_OF_SENSOR_RECORDS
          value: "1000000"
        - name: KAFKA_URL
          value: "{{.Release.Name}}-cp-kafka-headless.{{.Release.Namespace}}:9092"
        - name: SCHEMA_REGISTRY_URL
          value: "http://{{.Release.Name}}-cp-schema-registry.{{.Release.Namespace}}:8081"
        - name: HEALTHY_RATE
          value: "0.999"
        - name: WITH_LOG
          value: "true"
        image: {{ index .Values "fh-producer" "image" }}
        name: fh-producer-normal
        resources: {}
      restartPolicy: Always
status: {}
