apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.Release.Name}}-fh-producer-dangerous"
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app.kubernetes.io/name: "{{.Release.Name}}-fh-producer-dangerous"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{.Release.Name}}-fh-producer-dangerous"
    spec:
      containers:
      - env:
        - name: NUM_OF_PEOPLE
          value: "10"
        - name: NUM_OF_PEOPLE_PER_ITERATION
          value: "1"
        - name: HEALTHY_RATE
          value: "0.4"
        - name: KAFKA_URL
          value: "{{.Release.Name}}-cp-kafka-headless.{{.Release.Namespace}}:9092"
        - name: SCHEMA_REGISTRY_URL
          value: "http://{{.Release.Name}}-cp-schema-registry.{{.Release.Namespace}}:8081"
        - name: WITH_LOG
          value: "true"
        image: {{ index .Values "fh-producer" "image" }}
        name: fh-producer-dangerous
        resources: {}
      restartPolicy: Always
status: {}
