apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{.Release.Name}}-fh-throughput-alerts"
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app.kubernetes.io/name: "{{.Release.Name}}-fh-throughput-alerts"
spec:
  selector:
    matchLabels:
      app: "{{.Release.Name}}-fh-throughput-alerts"
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{.Release.Name}}-fh-throughput-alerts"
        app: "{{.Release.Name}}-fh-throughput-alerts"
    spec:
      terminationGracePeriodSeconds: 30
    spec:
      containers:
      - env:
        - name: KAFKA_URL
          value: "{{.Release.Name}}-cp-kafka-headless.{{.Release.Namespace}}:9092"
        - name: SCHEMA_REGISTRY_URL
          value: "http://{{.Release.Name}}-cp-schema-registry.{{.Release.Namespace}}:8081"
        - name: MAIN_CLASS
          value: "com.fh.throughput.ThroughputAlertsKt"
        image: {{ index .Values "fh-throughput" "image" }}
        name: "{{.Release.Name}}-fh-throughput-alerts"
        volumeMounts:
        - name: kafkastreamsdir
          mountPath: /tmp/kafka-streams
        resources:
{{ toYaml (index .Values "fh-throughput" "resources") | indent 10 }}
      restartPolicy: Always
      volumes:
      {{- if not (index .Values "fh-throughput" "persistence" "enabled") }}
      - name: kafkastreamsdir
        emptyDir: {}
      {{- end }}
  {{- if (index .Values "fh-throughput" "persistence" "enabled") }}
  volumeClaimTemplates:
  - metadata:
      name: kafkastreamsdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "{{ (index .Values "fh-throughput" "persistence" "size") }}"
      {{- if (index .Values "fh-throughput" "persistence" "storageClass") }}
      {{- if (eq "-" (index .Values "fh-throughput" "persistence" "storageClass")) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ (index .Values "fh-throughput" "persistence" "storageClass") }}"
      {{- end }}
      {{- end }}
  {{- end }}
status: {}

